format="""
[â•­](#fab387) $all\
[â•°â•´](#fab387)$character
"""

# Prompt symbols 
[character]
success_symbol = "[ğŸˆ](#fab387 bold) â¯"
error_symbol = "[ğŸˆ](#f38ba8) â¯"
vicmd_symbol = "[ğŸˆ](#f9e2af) â¯"

[directory]
format = "[î‚¶]($style)[(bg:#fab387 fg:#fe640b)$path](bg:#fab387 fg:#fe640b)[î‚´ ]($style)"
style = "bg:#1e1e2e fg:#fab387"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#fab387 fg:#fe640b bold)$branch](bg:#fab387 fg:#fe640b)[î‚´ ]($style)"
style = "bg:#1e1e2e fg:#fab387"
