right_format='$cmd_duration'

format='''
[â•­â”€â•´$directory $all](bold #fab387)
[â•°â•´$character](bold #fab487)'''

add_newline = false

# Prompt symbols
[character]
success_symbol = "[ğŸˆ â¯](#fab387 bold)"
error_symbol = "[ğŸˆ â¯](#f38ba8)"
vicmd_symbol = "[ğŸˆ â¯](#f9e2af)"

[directory]
format = "[î‚¶]($style)[(bg:#fab387 fg:#fe640b)$path](bg:#fab387 fg:#1e1e2e)[î‚´]($style)"
style = "bg:#1e1e2e fg:#fab387"

[line_break]
disabled = true
