right_format = '$cmd_duration'

format='''
[â•­â”€$directory $all](bold #cba6f7)
[â•°â•´$character](bold #cba6f7)'''

add_newline = false

# Prompt symbols
[character]
success_symbol = "[ğŸˆ â¯](#cba6f7 bold)"
error_symbol = "[ğŸˆ â¯](#f38ba8)"
vicmd_symbol = "[ğŸˆ â¯](#f9e2af)"

[directory]
format = "[î‚¶]($style)[(bg:#cba6f7 fg:#fe640b)$path](bg:#cba6f7 fg:#1e1e2e)[î‚´]($style)"
style = "bg:#1e1e2e00 fg:#cba6f7"

[line_break]
disabled = true
